### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by V02460** [davidhewitt/pythonize#33]
Currently it’s not clear how this project is licensed. The MIT identifier in `Cargo.toml` is not sufficient, because there are a lot of different variations of the MIT/BSD license (see this [list of SPDX identifiers](https://spdx.org/licenses)). Additionally, this kind of license often requires its text to be included. Please clarify the license you are publishing the code under by adding a LICENSE file to the repo.

Here is the license matching your identifier: https://spdx.org/licenses/MIT.html

Background: I’m planning on packaging pythonize for Fedora, but that is only possible if it’s clear how this project is licensed.

**Comment by davidhewitt** [comment]
Thanks and sorry for the slow response - added!
